spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sport_health?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 配置监控统计
      webStatFilter:
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        # 配置登录账号与密码
        login-username: root
        login-password: root
      filter:
        stat:
          enabled: true
          # 记录慢SQL
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss # 设置时间格式化
    time-zone: GMT+8 # 设置时区
  # 设置mvc path
  mvc:
    servlet:
      path: /api
server:
  port: 9000
mybatis-plus:
  type-enums-package: com.xzc.sport.health.modules.role.Role
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl






